<?xml version="1.0" encoding="utf-8"?><Database Name="CourseSignUps" Class="Applicants_DataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=CourseSignUps;Integrated Security=True" SettingsObjectName="Applicants.Data.Properties.Settings" SettingsPropertyName="CourseSignUpsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Applicants" Member="Applicants">
    <Type Name="Applicant">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="Status" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>